### ISSUE TITLE
implement the functional logic of the newsfeed tab on the dashboard

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#107]
As a user of the TDC portal, I want a page where I can get clear and informative notifications about any updates regarding my activities (e.g., membership requests, changes to the datasets and organisations I follow), so that I can manage my interactions efficiently and stay informed about the status of my actions.

## Tasklist (TBD - updated by the developer)
* [add tasks]

## Acceptance Criteria
Given that I am on the dashboard page and on the newsfeed tab,
* [x] I can see user-specific notifications, regarding changes to my organisation and datasets based on CKAN activity stream
* [x] I can see updates on the status of my data requests
* [x] I can see a filter at the top of the page to filter by All, Organisations, Datasets
* [x] I can see and interact with categories on the left landside of the page to narrow down newsfeed by applying All, Organisations, Datasets,
* [x] I can see the "Community Guidelines" section displayed on the right, reminding me of best practices.

**Comment by Uchechukwu-Onye-Igbo** [comment]
### QA Feedback

Hello @muhammad-hassan11, kindly address these issues.

* the dataset approvals categories filter is filtering same thing as the datasets category
* the search bar does not work as expected. searching does not return any values
* the filter in the quick filter on top of the page does not give any result when you filter by datasets and dataset approval

**Comment by Gutts-n** [comment]
@Uchechukwu-Onye-Igbo, @muhammad-hassan11 added this comment in his PR 
![image](https://github.com/user-attachments/assets/19bcec3e-e4c4-4fb2-949b-0892b6cd73b9)

**Comment by Uchechukwu-Onye-Igbo** [comment]
> @Uchechukwu-Onye-Igbo, @muhammad-hassan11 added this comment in his PR 
> ![image](https://github.com/user-attachments/assets/19bcec3e-e4c4-4fb2-949b-0892b6cd73b9)
> 

O I see. We'll wait

**Comment by Gutts-n** [comment]
@Uchechukwu-Onye-Igbo fixed.

**Comment by Uchechukwu-Onye-Igbo** [comment]
> @Uchechukwu-Onye-Igbo fixed.

Thanks... I'll check

**Comment by Uchechukwu-Onye-Igbo** [comment]
Note: adding the dropdown @nicolas-becker requested, in this PR: https://github.com/transport-data/tdc-data-portal/pull/136
