### ISSUE TITLE
Implement Dataset Details page design (no functionality logic)

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#11]
When I view the design implementation of the Dataset Details page for the data portal, I want to see a design implementation that matches the [Figma design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?page-id=0%3A1&node-id=513-34490&viewport=-3049%2C-751%2C0.24&scaling=min-zoom&starting-point-node-id=5%3A1091), so that it can be easily confirmed/validated that the UI/UX for the Dataset Details page is aligned with expectations.

### Note
* The following tabs/features on this page design should not be implemented; they are out of scope
  * the chart/visualisations
  * the discussion tab
  * the graph on the downloads tab

* Related dataset should be included as a tab on this page

## Tasklist (TBD provided by the developer)
* [add tasklist]

## Acceptance Criteria
Given that i have access to the Dev instance and Figma design, then:
* [x] when i view the Dataset Details page UI/UX design implementation on the Dev instance, it matches the Figma Design
* [x] all agreed sections of the Dataset Details page Figma design are implemented with the same UI behaviour (without application logic/functionality) on the remote Dev instance

**Comment by Gutts-n** [comment]
To make tests there is this page: https://tdc-data-portal.vercel.app/@sample-org/sample-dataset

**Comment by nicolas-becker** [comment]
Looks good. A few comments:

- Is it possible to add the explanation to the "TDC Harmonized" tag when hovering over it? As in the Figma example.
- Please correct the typo in "takeaways", which is also present in the Figma design.
- Please replace the header in the Metadata section with "Overview"

Thank you!

**Comment by luccasmmg** [comment]
![image](https://github.com/user-attachments/assets/6340da92-e470-42f7-84a3-3d1a065992bb)

Was something changed in the Figma? I dont rememver the metadata text being this
![image](https://github.com/user-attachments/assets/24b33504-7145-422b-a173-9eba80bf3b71)

![image](https://github.com/user-attachments/assets/49c5f816-4f0d-4155-a38e-705b7aa3187c)

**Comment by nicolas-becker** [comment]
The Figma didn't change, no. But looks great now, thanks for the update!
