### ISSUE TITLE
Implement Data Provider page design (no functionality logic)

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#12]
When I view the Data Provider page design implementation for the data portal, I want to see a design implementation that matches the [Figma design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?page-id=0%3A1&node-id=725-135022&viewport=-3049%2C-751%2C0.24&scaling=min-zoom&starting-point-node-id=5%3A1091), so that it can be easily confirmed/validated that the UI/UX for the Data Provider page is aligned with expectations

## Tasklist (TBD provided by the developer)
* [add tasklist]

## Acceptance Criteria
given that i have access to the Dev instance and Figma design, then:

* [x] when i view the Data Provider page UI/UX design implementation on the Dev instance, it matches the Figma Design
* [x] all agreed sections of the Data Provider page Figma design are implemented with the same UI behaviour (without application logic/functionality) on the remote Dev instance

**Comment by nicolas-becker** [comment]
Looks good! 

- Please adapt the responsive behaviour of the TDC chart, as discussed in the sprint call.
- Please drop the question mark in "How TDC datasets works". Seems to be a mistake in the Figma.

Thank you!

**Comment by Gutts-n** [comment]
@nicolas-becker adjusted the changes requests, pointing out that I added a carousel to the TDC cards in the mobile version, pls take a look and give me feedback
