### ISSUE TITLE
Add Page Loader to Indicate Page Loading

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#129]
As a user of the TDC portal, I want a page loader to be displayed while a page is loading, so that I am visually aware when a page is being fetched or processed and I do not assume the platform is unresponsive.

## Tasklist (TBD - updated by the developer)
* [x] show loading status when page is fetching data or navigating

## Acceptance Criteria
Given that I am trying to navigate between pages on the TDC portal,
* [ ] I can see a progress bar and spinner on the page when I am loading a page
* [ ] Once the page loads, I can no longer see the loader

**Comment by willy1989cv** [comment]
Doc: https://github.com/transport-data/tdc-data-portal/tree/main/docs/page-loading-component
Test: https://github.com/transport-data/tdc-data-portal/actions/runs/11283433106/job/31382848017#step:14:493
