### ISSUE TITLE
Create "Add Data" Button Component to facilitate Login Check and Permission Validation for Dataset Creation

### ISSUE THREAD

**Issue by willy1989cv** [transport-data/tdc-data-portal#137]
As a user attempting to add data on the TDC portal, I want to be prompted to log in if I am not already logged in, so that I can authenticate myself before proceeding to dataset creation. Additionally, if I do not have the necessary permissions to create the content, I want to be informed of this in an error message after I tried to create a dataset, so that I am aware of my access limitations and understand why I cannot perform the action.

## Tasklist (TBD - updated by the developer)
* [x] check wheater user is logged in or not when trying to access private page
* [x] redirect to first requested page after successufly login

## Acceptance Criteria
Given that I want to add data to the TDC portal using the "add data" button on any of the pages it is present,
* [ ] I will be prompted in a pop message to log in if I am not already logged in
* [ ] I should be lead to the dataset creation flow, if/when I am logged in
* [ ] If I do not have access to create dataset, I should get an error message to this effect when i try to finalize the dataset creation steps.

**Comment by willy1989cv** [comment]
Doc: https://github.com/transport-data/tdc-data-portal/tree/main/docs/protected-routes
Test: https://github.com/transport-data/tdc-data-portal/actions/runs/11274973194/job/31355328106#step:14:472

**Comment by nicolas-becker** [comment]
Following our discussion here: https://github.com/transport-data/tdc-data-portal/issues/55#issuecomment-2438179454, this is done. Thank you!
