### ISSUE TITLE
Implement FAQ page design (no functionality logic)

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#14]
When I view the FAQ page design implementation for the data portal, I want to see a design implementation that matches the [Figma design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?page-id=0%3A1&node-id=10-53876&viewport=-3049%2C-751%2C0.24&scaling=min-zoom&starting-point-node-id=5%3A1091), so that it can be easily confirmed/validated that the UI/UX for the FAQ page is aligned with expectations

## Tasklist (TBD provided by the developer)
* [add tasklist]

## Acceptance Criteria
given that i have access to the Dev instance and Figma design, then:

* [ ] when i view the FAQ page UI/UX design implementation on the Dev instance, it matches the Figma Design
* [ ] all agreed sections of the FAQ page Figma design are implemented with the same UI behaviour (without application logic/functionality) on the remote Dev instance

**Comment by osahon-okungbowa** [comment]
@luccasmmg
So small things to fix 
- [ ] the link for the Full list of participating groups should point to the "Partner & Donor page"
- [ ] the FAQ page is not linked in the footer

**Comment by luccasmmg** [comment]
> [@luccasmmg](https://github.com/luccasmmg) Some small things to fix
> 
> * [x]  the link for the Full list of participating groups should point to the "Partner & Donor page"[x]  the FAQ page is not linked in the footer

Done

**Comment by nicolas-becker** [comment]
Looks good already, I've only got a few minor comments:

- The text under "About Transport Data Commons" appears to be in block format (differing spaces), which is not consistent with the other pages on the site.
- The order of the questions does not fully align with the Figma template. E.g. "What are the benefits of being a registered user?" should be the last question within the "Getting Started" section.
- Question marks are missing for most of the questions. Including in the contact form (What can we help you with?).
- Please correct the spelling in "I _don't_ see my organisation. What should _I_ do?"
- The question "What about browser support?" is missing
- The title "Still need help?" seems to be indented.

Happy to provide further clarification if needed. Thank you!

**Comment by luccasmmg** [comment]
As @osahon-okungbowa pointed out , i left the questions as it its since those are just dummy values, and removed the `justify` from the first text + aligned vertically the "Still need help" with the list of questions

**Comment by nicolas-becker** [comment]
Great, thanks!

**Comment by luccasmmg** [comment]
Added documentation on how it works here https://github.com/transport-data/tdc-data-portal/tree/main/docs/static-pages/faq
