### ISSUE TITLE
Implement the functionality of account management functions

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#156]
As a registered user on the TDC portal, I want to easily access my dashboard, and logout from any page of the portal, so that I can have a seamless experience on the platform. 

## Tasklist (TBD - updated by developer)
* [add task]

## Acceptance Criteria
Given that I am a logged in user of the TDC portal,
* [ ] I can log out by clicking on a button that show up in a dropdown when I click on my user icon
* [ ] I click on the dropdown from my profile icon and see button to navigate to the newsfeed tab of my dashboard
* [ ] I can click on the settings button and be lead to the settings tab, where i can manage sysadmins and API keys if i am a sysadmin already.
* [ ] I can click on the settings button and be lead to the settings tab, where i can manage my API keys.

**Comment by Uchechukwu-Onye-Igbo** [comment]
### Additional Improvement

Sysadmin Management

- Add a new tab on the dashboard called “User Management”. Lead users to this tab when they click on “User Management” from the profile dropdown.
- As a sysadmin, you can view a list of all users who have sysadmin privileges on the portal.
- You have the ability to remove users from the sysadmin role.
- Additionally, there is an option to add new users as sysadmins, granting them the necessary administrative privileges. It should be an input field where they can type the name of any user in the system and it shows up for them to make the user a sysadmin.

API key Management

- Add a new tab on the dashboard called “User Management”. Lead users to this tab when they click on “User Management” from the profile dropdown.
- Authenticated users have access to manage their API keys.
- They can generate new API keys when needed.
- Users also have the option to delete any previously created API keys to revoke access.

@muhammad-hassan11 please take note.

**Comment by muhammad-hassan11** [comment]
PR link: https://github.com/transport-data/tdc-data-portal/pull/162

**Comment by Uchechukwu-Onye-Igbo** [comment]
### Additional Feedback

**API Token**

- Make copy button legible
- update colour scheme of the create token button
- add a confirmation dialogue when deleting token
- filter out the frontend token so users don't see them or even delete it
- ensure ckan allows duplicate names for tokens

**Sysadmin**

- "User demoted..." should be something like "user removed from sysadmin"

**Comment by Uchechukwu-Onye-Igbo** [comment]
Hi @muhammad-hassan11 

Thanks. this works well now. Good 👍
