### ISSUE TITLE
Add dataset details page for private and draft dataset

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#157]
When i am on the TDC portal and i visit a specific private or draft dataset, i want to see metadata and data for the specific dataset, so that i can know more about the dataset and download any data on the dataset.
Hint: implementation for [this design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=513-34490&node-type=FRAME&t=R30kSWgwuTFdsRKI-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1091)
Implementation note: this should be a different url, not the same one where public datasets can be seen

## Tasklist (TBD)
* [add tasks]

## Acceptance Criteria
Given i visit a specifc draft or private dataset on the TDC portal, then:
- [x] i see the dataset title
- [x] i see the dataset description and other agreed upon metadata in the Overview from the [Figma Design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=513-34490&node-type=FRAME&t=R30kSWgwuTFdsRKI-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1091)
- [ ] ~~i see a tabular preview of the dataset data in the Dataset tab~~
- [x] i see other metadata in the Metadata tab
- [ ] ~~i see a link to existing discussions and a button to create new discussions when i view the Discussions tab~~
- [x] i see a list resources and documents which i can download when i visit the Downloads tab

**Comment by Uchechukwu-Onye-Igbo** [comment]
### QA Note

Thanks @luccasmmg, this works.

However, when you are done making the changes to #101 , kindly remember to update this one as well. That is when I will consider this done.

**Comment by luccasmmg** [comment]
?
![image](https://github.com/user-attachments/assets/9c3cecb0-eb37-4137-bd11-11261c3c1394)

**Comment by Uchechukwu-Onye-Igbo** [comment]
> ? ![image](https://private-user-images.githubusercontent.com/11317382/378395766-9c3cecb0-eb37-4137-bd11-11261c3c1394.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MTAwNzQsIm5iZiI6MTcyOTUwOTc3NCwicGF0aCI6Ii8xMTMxNzM4Mi8zNzgzOTU3NjYtOWMzY2VjYjAtZWIzNy00MTM3LWJkMTEtMTEyNjFjM2MxMzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDExMjI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxM2ZhMTQ3NTRkMjVkOWYzOTQ5ZmIyOTk5YzdhOTU2MDU0NzU2MWFjNTYzYjI4Y2RjODE5YmIzN2UxYTNiMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yo72ENr5NFvze-RUyJBZ5VxpR9xMnXJp9HNw2h-EBhw)

i can see you just moved the issue to QA. I will take another look. Thanks
