### ISSUE TITLE
Develop Technical Documentation (Developer Guide) for the TDC Portal

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#179]
As a developer, when I am learning about the TDC portal, I want to have access to comprehensive technical documentation (developer guide), so I can effectively understand how the portal was built and where to find the necessary code and tools used.

## Tasklist (TBD - updated by the developer)
* [x] I have a resource that
   * [x] explain the  features of the TDC portal.
* [x] I can read a technical documentation which spells out the technologies used and how I can maintain them
* [x] I want a resource on how I can contact support, report issues, and stay updated with portal feature enhancements post deployment. 

## Acceptance Criteria
Given that I am a developer, and I am learning how the portal was built;
* [ ] I have a technical documentation which spells out the technologies used and how I can maintain them

**Comment by Uchechukwu-Onye-Igbo** [comment]
Hello @Gutts-n please where is the link to the technical documentation? please add it here for review.

**Comment by Gutts-n** [comment]
@Uchechukwu-Onye-Igbo https://github.com/transport-data/tdc-data-portal/blob/main/docs/technical-documentation/README.md
