### ISSUE TITLE
Implement Dashboard page for the data provider (no functionality logic)

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#18]
When I view the Dashboard page design implementation for the data portal, I want to see a design implementation that matches the [Figma design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?page-id=0%3A1&node-id=658-77537&viewport=-3049%2C-751%2C0.24&scaling=min-zoom&starting-point-node-id=5%3A1091), so that it can be easily confirmed/validated that the UI/UX for the Dashboard page is aligned with expectations

## Tasklist (TBD provided by the developer)
* [add tasklist]

## Acceptance Criteria
given that i have access to the Dev instance and Figma design, then:

* [ ] when i view the Dashboard page UI/UX design implementation on the Dev instance, it matches the Figma Design
* [ ] all agreed sections of the  Dashboard page Figma design are implemented with the same UI behaviour (without application logic/functionality) on the remote Dev instance

**Comment by osahon-okungbowa** [comment]
this can be tested/validated by visiting [/dashboard](https://tdc-data-portal.vercel.app/dashboard)
