### ISSUE TITLE
[improvement] Enhance Pagination Experience on Newsfeed Page

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#182]
When browsing the newsfeed on the TDC portal, I want a smooth and responsive pagination experience, so that I can easily navigate through updates without lag or confusion and focus on the content.

## Tasklist (TBD - updated by the developer)
* [add tasks]

## Acceptance Criteria
Given that I am navigating content on the newsfeed page,
* [ ] when i am using the pagination implementation on the page, i should see all relevant content based on the category i select
* [ ] i can navigate the page smoothly by clicking on the page numbers and the direction arrows.
* [ ] I want my browser to only load the data that is necessary for what is currently visible on the screen so that I can use the page as soon as possible
* [ ] I want to be able to navigate the entire activity history, regardless of when the activity happened

**Comment by Uchechukwu-Onye-Igbo** [comment]
Hello @Gutts-n if you have reviewed this implementation, kindly update it to the right status. thank you

**Comment by nicolas-becker** [comment]
I was pointed here by @willy1989cv to flag the following issue:

The username of the user whose permission rights were changed is not displayed in the notification:
![image](https://github.com/user-attachments/assets/628e958a-43a3-4c5d-ac94-e4ede410a80f)

**Comment by Uchechukwu-Onye-Igbo** [comment]
> I was pointed here by [@willy1989cv](https://github.com/willy1989cv) to flag the following issue:
> 
> The username of the user whose permission rights were changed is not displayed in the notification: ![image](https://github.com/user-attachments/assets/628e958a-43a3-4c5d-ac94-e4ede410a80f)

hello @Gutts-n please take a look at this comment

**Comment by Gutts-n** [comment]
@nicolas-becker which of the notifications on the print should present the user that you changed?

**Comment by nicolas-becker** [comment]
> @nicolas-becker which of the notifications on the print should present the user that you changed? And how can I reproduce this notification on my newsfeed tab?

@Gutts-n The notifcation "**You** updated the user" should contain at least the name of the user. So in this case "**You** updated the user **vvilly89**". Better would be of course if the notification contained the full information that I updated the user from **member** to **editor** for **organizationX**.

You should be able te reproduce the error if you change a member's permission rights for an organization you are admin of.

**Comment by Gutts-n** [comment]
@Uchechukwu-Onye-Igbo I think that @willy1989cv is looking at it, we agreed via chat some days ago that he would fix this.

**Comment by willy1989cv** [comment]
@Gutts-n yes, I am looking at it right now

**Comment by willy1989cv** [comment]
Fixed.
![Image](https://github.com/user-attachments/assets/54b53b36-32af-4f23-8187-a310cd2ec138)

**Comment by nicolas-becker** [comment]
Hi @willy1989cv , the pagination itself is working fine, but I am not sure about this: https://github.com/transport-data/tdc-data-portal/issues/182#issuecomment-2483021369

Just to be sure, that I am testing the right thing: This notification appears when a user permission level is updated, right? It should appear both to the user and to the admin who has changed the permission level.

**Comment by Uchechukwu-Onye-Igbo** [comment]
> Hi @willy1989cv , the pagination itself is working fine, but I am not sure about this: [#182 (comment)](https://github.com/transport-data/tdc-data-portal/issues/182#issuecomment-2483021369)
> 
> Just to be sure, that I am testing the right thing: This notification appears when a user permission level is updated, right? It should appear both to the user and to the admin who has changed the permission level.

hello @willy1989cv 

have you seen this?

**Comment by nicolas-becker** [comment]
hi @Uchechukwu-Onye-Igbo,

I agree, yes. It is enough to show this info to the updated user. The sysadmin/admin gets a success message the moment he performs the action, so this should be enough.

Currently I am not getting the message on neither of the both sides

**Comment by Uchechukwu-Onye-Igbo** [comment]
> hi [@Uchechukwu-Onye-Igbo](https://github.com/Uchechukwu-Onye-Igbo),
> 
> I agree, yes. It is enough to show this info to the updated user. The sysadmin/admin gets a success message the moment he performs the action, so this should be enough.
> 
> Currently I am not getting the message on neither of the both sides

hello @nicolas-becker I am sorry, i must have confused you. users dont get that notificaiton when they have been made sysadmin. i misread your message.

when a user is upgraded, on their profile dropdown, they see a message that says they are now sysadmins. ![Image](https://github.com/user-attachments/assets/2ebf9206-2922-40cd-bc19-71d5dbbd770b)

@willy1989cv please can you check why Nico is not getting success message when they upgrade users to sysadmin?
