### ISSUE TITLE
Improve User Onboarding and Organization Membership Request Process

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#189]
When a non-existing user clicks the "log-in" button on the TDC portal, they should create an account and then go through the onboarding process, so that they can request organization membership among other things. 

When a user skips the onboarding step or wants to join another organisation at a later time, they should be able to request organization access from the dashboard, so that they can contribute data to the portal.

## Tasklist (TBD - updated by the developer)
* [add tasks]

### Use case 1
Given that I a user without an account on the portal, if I click on the "log in" button,
* [x] I should be lead to the SSO process of account creation.
* [x] I should be lead through the onboarding after creating an account.

### Use case 2
Given that I skipped the onboarding step and/or want to join an organisation at a later time,
*  [x] I can see a button on my dashboard that will lead me directly to the step of the join an organisation step of the onboarding  flow 
* [x] I can request the creation of a new organisation
* [x] I can request to join any organisation on the portal.

**Comment by nicolas-becker** [comment]
Bug on the create Org function mentioned here: #180

**Comment by nicolas-becker** [comment]
Bug seems to be fixed https://github.com/transport-data/tdc-data-portal/issues/189#issuecomment-2491916311 Closing the issue
