### ISSUE TITLE
Improve Email Field Requirement for Inviting Friends and Link Bell Icon to Newsletter Page

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#190]
When a user is inviting friends and colleagues through the "Invite friends & colleagues" form in the onboarding flow, they should be required to enter email addresses if they are attaching a message, so that the invitation can be sent successfully. However, if the user is not sending a message, the email field should not be required.

When a user clicks on the bell icon in the portal's navbar, then they should be redirected to the newsletter subscription page, so that they can subscribe to the TDC news letter.
Newsletter link: https://civicrm.changing-transport.org/form/tdci-newsletter 

## Tasklist (TBD - updated by developer)
* [x] make the email field required for me when click to enter a message in the message box.
* [x] If I do not click to enter a message, the email field should remain optional. 
* [x] I am redirected to the newsletter subscription page

### Use case 1
Given that I am a user going through the onboarding flow and want to invite a friend,
* [ ] make the email field required for me when click to enter a message in the message box.
* [ ] If I do not click to enter a message, the email field should remain optional. 

### Use case 2
Given that I am a user, if i click on the bell icon in the navbar,
* [ ] I am redirected to the newsletter subscription page

**Comment by Uchechukwu-Onye-Igbo** [comment]
Hello @willy1989cv 

The behavior for the email is working but now the message field is now required. if you enter the email, it now expects the message before user can submit.

**Comment by willy1989cv** [comment]
> The behavior for the email is working but now the message field is now required. if you enter the email, it now expects the message before user can submit.

fixed

**Comment by Uchechukwu-Onye-Igbo** [comment]
I think the logic makes sense. thanks @willy1989cv

**Comment by willy1989cv** [comment]
@Uchechukwu-Onye-Igbo please test again.
