### ISSUE TITLE
Add Country Filter to Search Bar

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#196]
When I'm using the search bar on the TDC portal, I want the option to filter results by country and region so that I can quickly find datasets relevant to specific geographic areas. This filter when used should be applied in the advanced search options, with "in country" as the label for the country filter and "in region" as the label for the region filter.

## Tasklist (TBD - updated by the developer)
* [x] add "country" filter to SearchBar component
* [x] activate advanced search options when searching for location on the search page
* [x] provide documentation on how to add/update new fields to the searchbar

## Acceptance Criteria
Given that I am using the search bar to find results,
* [ ] I can see "in country" filter for me to use to find data specifically for a country
* [ ] in addition to "in country", i should see "in region" among the filter options
* [ ] when the user applies a country or region filter from the main search bar, it should appear and be active in the advanced search options.
* [ ] the search results should update to reflect the applied country and regions right in the search bar in the browse page.

**Comment by willy1989cv** [comment]
Documentation: https://github.com/transport-data/tdc-data-portal/tree/main/docs/search-bar-component#adding-a-new-filter-parameter-to-the-searchbar-component

**Comment by Uchechukwu-Onye-Igbo** [comment]
Works well @willy1989cv thanks
