### ISSUE TITLE
Fix Issues with Joining New Organizations and Creating New Organizations in Production

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#202]
When I attempt to join an organization or request the creation of a new one during the onboarding process or through the organization joining modal in the production app of the portal, the process should work seamlessly, so that I can participate fully in the platform and contribute datasets without encountering errors.

Some screenshots below
![Image](https://github.com/user-attachments/assets/a3772209-529c-4f50-b079-c26677d3083d)
![Image](https://github.com/user-attachments/assets/a8afcf5e-0f5b-4df7-97d6-4fd30bf51f90)
![Image](https://github.com/user-attachments/assets/608816bd-d877-41c7-bb4a-849926a8c15b)
![Image](https://github.com/user-attachments/assets/dba8491f-302e-43e5-9108-aa257ae1b033)

## Tasklist (TBD - updated by the developer)
* [add tasks]

## Acceptance Criteria
Given that I am on the production app,
* [x] I can seamlessly request to join an organisation or the creation of a new one when going through the onboarding steps.
* [x] I can seamlessly request to join an organisation or the creation of a new one when going through the org joining modal on my dashboard.

**Comment by Uchechukwu-Onye-Igbo** [comment]
hi @demenech please take a look at this comment https://github.com/transport-data/tdc-data-portal/issues/180#issuecomment-2491866486

**Comment by demenech** [comment]
hey @Uchechukwu-Onye-Igbo @nicolas-becker 
currently working on this, I believe I found the issue

**Comment by demenech** [comment]
@Uchechukwu-Onye-Igbo this has been fixed. Nicholas also confirmed it's working (in case you want to move it to done)

**Comment by Uchechukwu-Onye-Igbo** [comment]
> @Uchechukwu-Onye-Igbo this has been fixed. Nicholas also confirmed it's working (in case you want to move it to done)

thanks bro. i will check
