### ISSUE TITLE
Implement Functionality logic for Home page design

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#22]
When I visit the TDC portal Homepage, I want to be greeted with an informative and engaging homepage based on the [figma design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=5-1091&node-type=FRAME&t=R30kSWgwuTFdsRKI-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1091&show-proto-sidebar=1)
so that I can easily understand the purpose of the platform, explore available datasets, and contribute my own data to enhance the portal’s offerings.

## Tasklist (TBD - to be updated by the developer)
* [x] pull datasets from ckan api
* [x] get testimonials from github content folder
* [x] get faqs from github content folder
* [x] integration test
* [x] documentation

## Acceptance Criteria
* [ ] The homepage design matches the provided Figma design, including all visual elements, text, and layout structure.
* [ ] The following sections of the homepage are implemented according to the figma design;
    * [ ] the hero section
    * [ ] the recently added section
    * [ ] the data contribution section
    * [ ] the FAQ section
    * [ ] the newsletter section 
* [ ] That all text content is displayed as per the design, including headings, subheadings, descriptions.
* [ ] That all the links connected to other pages are wired up
* [ ] That integration test is written for this implementation

**Comment by Verena205** [comment]
Regarding the video on the home page, we discussed in the data group that we will not have a video in time. We should thus rather add a photo as a placeholder for a video if possible. It should be set-up in a way to allow a later replacement with a video of our choice. Is this feasible?

**Comment by willy1989cv** [comment]
@Uchechukwu-Onye-Igbo regarding the FAQ's, what should be the order of the questions?
Should we sort by:
- date modified desc/asc?
- date created desc/asc?
- a `order` field in the md file.


![image](https://github.com/user-attachments/assets/49fa01bf-d9a9-4689-a9e8-5eb2eab10386)

**Comment by willy1989cv** [comment]
Docs: https://github.com/transport-data/tdc-data-portal/tree/main/docs/home-page
Test: https://github.com/transport-data/tdc-data-portal/actions/runs/11266081869/job/31328986006#step:14:293

**Comment by Uchechukwu-Onye-Igbo** [comment]
Question

@willy1989cv is the FAQ section of this page weird up to the markdown file we are using to power FAQs?

**Comment by willy1989cv** [comment]
> @willy1989cv is the FAQ section of this page weird up to the markdown file we are using to power FAQs?

Yes @Uchechukwu-Onye-Igbo, this section uses the same files as FAQ page.

**Comment by willy1989cv** [comment]
For hero section image:
Default **Dimension**: 540x405 pixels
Image **Format**: can be jpg or png

See how to configure how to include image/video here:
https://github.com/transport-data/tdc-data-portal/tree/main/docs/home-page#featured-asset

**Comment by nicolas-becker** [comment]
Thanks for the information for the image! Could you just quickly add it to the docs, so to preserve the information? I will then move the issue to done.

**Comment by willy1989cv** [comment]
Updated [here](https://github.com/transport-data/tdc-data-portal/blob/main/docs/home-page/README.md#featured-asset)

**Comment by nicolas-becker** [comment]
Thanks @willy1989cv !
