### ISSUE TITLE
Implement GitHub SSO (Single Sign-On) Authentication for the Portal

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#23]
When I want to access the portal, I want to be able to log in using my GitHub account via Single Sign-On (SSO), so that I can quickly and securely access the portal without needing to create and remember a separate set of login credentials.

## Tasklist (TBD - to be updated by the developer)
* [x] create .env variables
* [x] setup github oauth on next project
* [x] remove google authentication
* [x] update Header component to support authenticated user

## Acceptance Criteria

GitHub SSO Integration:
* [x] That the portal supports GitHub SSO, allowing users to authenticate using their GitHub credentials.
* [x] That a "Sign in with GitHub" button is prominently displayed on the login and signup pages and functions correctly.

User Authentication:
* [x] That upon selecting the "Sign in with GitHub" option, users are redirected to the GitHub authentication page to enter their credentials.
* [x] That if the user grants permission, they are redirected back to the portal and automatically logged in.
* [x] That if the user cancels the authentication or denies permission, they are redirected back to the login page with an appropriate error message.

Integration Testing:
* [ ] That integration testing is done for this implementation

**Comment by Gutts-n** [comment]
Blocked waiting help of @Mikanebu to check the errors of the CI/CD to build CKAN's image run to fix them

Action: https://github.com/transport-data/tdc-data-portal/actions/runs/10833439119

**Comment by Uchechukwu-Onye-Igbo** [comment]
> Blocked waiting for the help of [@Mikanebu](https://github.com/Mikanebu) to check the errors of the CI/CD to CKAN's image run (it just presents a generic error and I couldn't find the logs that generated it) to fix them
> 
> Action: https://github.com/transport-data/tdc-data-portal/actions/runs/10833439119

Hi @Gutts-n please confirm if this issue is still blocked. Thanks.

**Comment by Mikanebu** [comment]
Hi @Gutts-n! Have you tested this locally first? I am adding step to get container logs and see what is the issue.

**Comment by Mikanebu** [comment]
@Gutts-n I added step to check ckan container and print logs if it is `unhealthy`.

**Comment by nicolas-becker** [comment]
This is working fine, thank you. Just one question: Is it possible to change the active account? When I log out on the portal and log in again, I am automatically directed to my account, without a prompt asking for the account I want to log in with. Is this the usual behaviour, as I am logged in to my GitHub account on the same browser?

**Comment by willy1989cv** [comment]
Yes @nicolas-becker. What you're seeing is likely because you're only signed in with one GitHub account on your browser. If you had more than one, it would take you to the GitHub screen to choose which account to use. So, it's just auto-picking the only one it sees.

![image](https://github.com/user-attachments/assets/e45f8c7c-11d0-4b52-8786-a464c2082e53)

**Comment by nicolas-becker** [comment]
Okay, thanks for the clarification @willy1989cv . So I would need to sign out of my current github session in the browser in order to be able to sign in with some other account?

**Comment by willy1989cv** [comment]
> Okay, thanks for the clarification @willy1989cv . So I would need to sign out of my current github session in the browser in order to be able to sign in with some other account?

No, @nicolas-becker you wouldn't need to sign out. You can just add a new account from the top-right corner of the GitHub header, like this:
![image](https://github.com/user-attachments/assets/fcee8b83-43fe-4270-86d6-993a549abbea)

**Comment by willy1989cv** [comment]
Hi @nicolas-becker is this clear? Let us know if you need further clarification
