### ISSUE TITLE
Setup CI/CD pipeline for remote Dev Environment

### ISSUE THREAD

**Issue by osahon-okungbowa** [transport-data/tdc-data-portal#3]
## Description

As a DevSecOps Engineer, I want to setup a CI/CD pipeline for the remote Dev environment of the data portal services/components, so that the development team CONTINUOUSLY and AUTOMATICALLY ADD, TEST and DEPLOY incremental functionalities and features for the portal on the remote Dev instance.

## Tasklist (TBD)
- [ ] create the necessary documentation on how to create and operate/trigger the CI/CD pipeline
- [x] setup google build CI/CD in config repo for building dockerfile from client repo

## Acceptance Criteria
given that I have the necessary access and permission to the project code repo, then:
- [ ] when I make a Pull Request (PR) on a specified branch for Dev, the CI/CD pipeline runs the integration test suites within its internal dockerized environment
- [ ] the PR on the specified Dev branch can ONLY BE MERGED when ALL integration tests run successfully
- [ ] a successfully merged PR triggers a deployment to the remote Dev instance
- [ ] the triggered deployment on the Dev branch is executed/run successfully without errors
- [ ] all the latest features/functionality from the triggered deployment are available to test on the Dev instance

**Comment by Mikanebu** [comment]
@Uchechukwu-Onye-Igbo Remote dockerfile build is configured. It triggers when you do any changes to main branch in dev environment. So this config repo https://github.com/datopian/dx-helm-tdc-dev uses this dockerfile from client's repo https://github.com/transport-data/tdc-data-portal/blob/main/ckan/Dockerfile.  cc @osahon-okungbowa

**Comment by osahon-okungbowa** [comment]
thanks @Mikanebu .

@luccasmmg please validate that the deployment works as devs expect/require

**Comment by nicolas-becker** [comment]
Is there a need to review this from our side?

**Comment by osahon-okungbowa** [comment]
@nicolas-becker no, there is no need. I'll move to `Done` now
