### ISSUE TITLE
Implement the Dataset Upload/creation flow (no functionality logic)

### ISSUE THREAD

**Issue by osahon-okungbowa** [transport-data/tdc-data-portal#35]
## Description
When I view the Dataset Upload Flow design implementation for the data portal, I want to see a design implementation that matches the [Figma design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=661-83593&node-type=FRAME&t=R30kSWgwuTFdsRKI-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1091), so that it can be easily confirmed/validated that the UI/UX for the dataset upload flow is aligned with expectations

## Tasklist (TBD - to be completed by Developer assigned)
- [add tasks]

## Acceptance Criteria
given that i have access to the Dev instance and Figma design, then:
- [ ] when i view the Dataset Upload Flow UI/UX design implementation on the Dev instance, it matches the Figma Design
- [ ] all agreed sections of the Dataset Upload Flow Figma design are implemented with the same UI behaviour (**without** application logic/functionality) on the remote Dev instance

**Comment by osahon-okungbowa** [comment]
@luccasmmg how to test this?

**Comment by osahon-okungbowa** [comment]
for now, we can test via https://tdc-data-portal.vercel.app/auth/old_signin

**Comment by nicolas-becker** [comment]
Do I need a Portal JS account to test this item?

**Comment by nicolas-becker** [comment]
How do I access the implemented data upload flow?

**Comment by luccasmmg** [comment]
> How do I access the implemented data upload flow?

We can provide you with a password and username, but i believe it cant be done here since its a public repo, i will leave to @osahon-okungbowa or @Uchechukwu-Onye-Igbo to do that

**Comment by nicolas-becker** [comment]
Thank you Luccas! I was provided with the temporary credentials, here are some comments:

- Maybe extend the title in the General section to "General Information about the Dataset", or something similar to the Figma.
- Not sure if "Slug" is a term every potential user is familiar with. Is this field required or could it be optional and filled out automatically based on the information provided? 
- There seems to be a small bug in the keyword section, as I was able to fill in more than 3 keywords, although it states "max. 3":
![Image](https://github.com/user-attachments/assets/7f83d0a7-7d9e-4a24-a525-703f0ed80839)

**Comment by osahon-okungbowa** [comment]
> Thank you Luccas! I was provided with the temporary credentials, here are some comments:
> 
> * Maybe extend the title in the General section to "General Information about the Dataset", or something similar to the Figma.
> * Not sure if "Slug" is a term every potential user is familiar with. Is this field required or could it be optional and filled out automatically based on the information provided?
> * There seems to be a small bug in the keyword section, as I was able to fill in more than 3 keywords, although it states "max. 3":
>   ![Image](https://private-user-images.githubusercontent.com/56161155/367230875-7f83d0a7-7d9e-4a24-a525-703f0ed80839.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NjUyNDUsIm5iZiI6MTcyNjc2NDk0NSwicGF0aCI6Ii81NjE2MTE1NS8zNjcyMzA4NzUtN2Y4M2QwYTctN2Q5ZS00YTI0LWE1MjUtNzAzZjBlZDgwODM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE2NTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZmFhN2JkOTUyNjYyYzBiNDZmZjA1MzdjYWRhZWQ1NWMyYjFkNzE4OWFmNzdlOTI5NzJhODJkNmFjN2U1NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ELETVUtj6Yta4nmQh1u0QkfiUjOqUJNs1uLRPjGnZ5A)

the observation made above will be fixed in the implementation ticket #45 .
So closing this
