### ISSUE TITLE
Implement the Events page design (no functionality logic)

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#36]
## Description
When I view the Events page design implementation for the data portal, I want to see a design implementation that matches the [Figma design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=130-33955&node-type=FRAME&t=R30kSWgwuTFdsRKI-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1091), so that it can be easily confirmed/validated that the UI/UX for the Events page is aligned with expectations

## Tasklist (TBD - to be completed by Developer assigned)
- [add tasks]

## Acceptance Criteria
given that i have access to the Dev instance and Figma design, then:
- [ ] when i view the Events page UI/UX design implementation on the Dev instance, it matches the Figma Design
- [ ] all agreed sections of the Events page Figma design are implemented with the same UI behaviour (**without** application logic/functionality) on the remote Dev instance

**Comment by osahon-okungbowa** [comment]
@willy1989cv this lacks proper documentation. please provide documentation 

cc @Uchechukwu-Onye-Igbo

**Comment by Uchechukwu-Onye-Igbo** [comment]
> [@willy1989cv](https://github.com/willy1989cv) this lacks proper documentation. please provide documentation
> 
> cc [@Uchechukwu-Onye-Igbo](https://github.com/Uchechukwu-Onye-Igbo)

@luccasmmg to handle this

**Comment by luccasmmg** [comment]
Done https://github.com/transport-data/tdc-data-portal/tree/main/docs/static-pages/events

**Comment by nicolas-becker** [comment]
Looks good! Also thanks for the docs. Could you just add a link from the About us page > Events section to the Events page? So this is connected (maybe on the "view all" button underneath). Thanks!

**Comment by willy1989cv** [comment]
@nicolas-becker this is fixed now. can you please review again and let us know?
https://tdc-data-portal.vercel.app/about-us

**Comment by nicolas-becker** [comment]
Perfect, thanks!
