### ISSUE TITLE
Implement the Contact Us page of the TDC portal

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#38]
## Description
As a user of the TDC portal, I want access to a "Contact Us" page that provides a means to contact TDC for support, data inquiries, partnerships, log issues or ask questions, so that I can easily get in touch with the appropriate team for assistance.

## Tasklist (TBD - to be completed by Developer assigned)
- [x] Email contact section
- [x] Data-related section
- [x] Documentation

## Acceptance Criteria
given that i have access to the TDC portal and I am viewing the contact us page:
- [x] I can see the message welcoming/inviting me to make my inquiry 
- [x] I can click on the displayed email to open my email client in a new tab/window with the displayed email prefilled ready for me to compose an email.
- [x] I can click on the provided GitHub link and be redirected to GitHub project board to log any issues I might have.

### Text for the page:

Contact Us

Thank you for your interest in Transport Data Commons!

For general inquiries, to join the initiative, or any other questions, please feel free to reach out to us via email:

📧 Email: [contact@transport-data.org](mailto:contact@transport-data.org)

Data-Related Issues
If you have questions, suggestions, or encounter issues related to our data, we encourage you to use our GitHub Issues board. This helps us respond faster and track all data-related feedback effectively.

[🔗 GitHub Issues Board](https://github.com/orgs/transport-data/projects/4/views/1): Submit an Issue on GitHub

We appreciate your contributions and feedback!

**Comment by Uchechukwu-Onye-Igbo** [comment]
> No Contact Form should be shown (as in the Figma). Instead, we would just showcase a text:
> 
> Contact Us Thank you for your interest in Transport Data Commons!
> 
> For general inquiries, to join the initative, or any other questions, please feel free to reach out to us via email:
> 
> 📧 Email: [contact@transport-data.org](mailto:contact@transport-data.org)
> 
> Data-Related Issues If you have questions, suggestions, or encounter issues related to our data, we encourage you to use our GitHub Issues board. This helps us respond faster and track all data-related feedback effectively.
> 
> 🔗 GitHub Issues Board: Submit an Issue on GitHub
> 
> We appreciate your contributions and feedback!
> 
> --> Currently, we do not have a GitHub Issues board set up that we could link to. Would it be possible for you to set it up within the repository and then add a link? Thx

thanks for clearing this up @Verena205. 

we made this https://github.com/orgs/transport-data/projects/4/views/1 board following your direction, but it is private. we need an admin of the TDC repo to make it public so users can use it to log issues.

thanks

**Comment by Verena205** [comment]
I think Paul or Nicolas should be able to change this. Kindly let them know there is need for action. Thanks

**Comment by willy1989cv** [comment]
Doc: https://github.com/transport-data/tdc-data-portal/tree/main/docs/contact-us

**Comment by Uchechukwu-Onye-Igbo** [comment]
Thanks @willy1989cv,

Can we however have this? when user clicks on the email to send on, the user's email client should open in a new tab, as in the acceptance criteria above.

**Comment by willy1989cv** [comment]
> Can we however have this? when user clicks on the email to send on, the user's email client should open in a new tab, as in the acceptance criteria above.

The `mailto:` link cannot directly open in a new tab because it triggers the user's default email client rather than opening a webpage. HTML's `target="_blank"` attribute, which is used to open links in a new tab, does not work with `mailto:` links.

@Uchechukwu-Onye-Igbo

**Comment by nicolas-becker** [comment]
Looks and works fine. Please update the link to the following GitHub Discussions category for user feedback: 

https://github.com/orgs/transport-data/discussions/categories/user-feedback

**Comment by Gutts-n** [comment]
@nicolas-becker I've pushed the change of the URL.

**Comment by nicolas-becker** [comment]
Thank you!
