### ISSUE TITLE
Implement the Geography page (no functionality logic)

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#39]
## Description
When I view the Geography page design implementation for the data portal, I want to see a design implementation that matches the [Figma design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=10-26857&node-type=FRAME&t=R30kSWgwuTFdsRKI-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1091), so that it can be easily confirmed/validated that the UI/UX for the Geography page is aligned with expectations

## Tasklist (TBD - to be completed by Developer assigned)
- [add tasks]

## Acceptance Criteria
given that i have access to the Dev instance and Figma design, then:
- [x] when i view the Geography page UI/UX design implementation on the Dev instance, it matches the Figma Design
- [x] all agreed sections of the Geography page Figma design are implemented with the same UI behaviour (**without** application logic/functionality) on the remote Dev instance

**Comment by Gutts-n** [comment]
@Uchechukwu-Onye-Igbo and @osahon-okungbowa will we present a tooltip to the countries that don't have datasets?

**Comment by osahon-okungbowa** [comment]
@Gutts-n yes we should present tooltips for countries that don't have datasets. in this case, the tooltip will display the name, but no `dataset` information. We can do this during the implementation phase

**Comment by nicolas-becker** [comment]
Is the map displayed correctly based on the geojson file we provided? We've noticed some inconsistencies, such as the border between Morocco and Western Sahara.

Additionally, could you implement the responsiveness from the Figma design when hovering over a country? In the Figma, this feature is only available for the US, where the country's area expands slightly upon hover. This helps improve the understanding of which area is currently selected on the map.

**Comment by osahon-okungbowa** [comment]
@nicolas-becker this ticket is strictly to provide the design guideline/framework. There is a spearate ticket for implementation based on the geojson). We have not started work on that ticket.

i'll let @Gutts-n respond to your other question on responsiveness

**Comment by nicolas-becker** [comment]
Alright, thanks for the clarification @osahon-okungbowa

**Comment by nicolas-becker** [comment]
@Gutts-n perfect, thank you!
