### ISSUE TITLE
Implement Home page design (no functionality logic)

### ISSUE THREAD

**Issue by osahon-okungbowa** [transport-data/tdc-data-portal#4]
## Description
when i view the Home Page design implementation for the data portal, I want to see a design implementation that matches the [Figma design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?page-id=0%3A1&node-id=5-1091&viewport=-3049%2C-751%2C0.24&scaling=min-zoom&starting-point-node-id=5%3A1091), so that it can be easily confirmed/validated that the UI/UX for the Home page is aligned with expectations

## Tasklist (TBD - to be completed by Developer assigned)
- [x] Implement Header
- [x] Implement Footer 
- [x] Hero with Video
- [ ] ~~Dynamic Searchbar with filtering options and recent searches~~ (This will be addressed in a separate issue)
- [x] Partners showcase
- [x] Recenlty added Datasets section
- [x] Data contribution Section
- [x] Accordion Testimonials section
- [x] FAQ's
- [x] Signup Form

## Acceptance Criteria
given that i have access to the Dev instance and Figma design, then:
- [x] when i view the Home page UI/UX design implementation on the Dev instance, it matches the Figma Design
- [x] all agreed sections of the Home page Figma design are implemented with the same UI behaviour (**without** application logic/functionality) on the remote Dev instance

**Comment by osahon-okungbowa** [comment]
@willy1989cv please review your Home page implementation.
Specifically, the section that list members of the TDCI. there is a fade animation that loops through all the pages of the members
moving back to `in progress`

cc @Uchechukwu-Onye-Igbo 


![Image](https://github.com/user-attachments/assets/9d4b3562-7810-4273-8501-5007c05fc0c4)

**Comment by willy1989cv** [comment]
> the section that list members of the TDCI

Fixed here: https://github.com/transport-data/tdc-data-portal/pull/28

@osahon-okungbowa @Uchechukwu-Onye-Igbo

**Comment by osahon-okungbowa** [comment]
looks good

**Comment by nicolas-becker** [comment]
Great! Just one comment:

- The white button under the "Contribute Data to the Transport Data Commons" section is supposed to say "Learn more" instead of "Add data". 

Thank you!

**Comment by osahon-okungbowa** [comment]
Based on this comment: https://github.com/transport-data/tdc-data-portal/issues/4#issuecomment-2346603130

@demenech please update the appropriate button to say "Learn more" and have it merged. It should be very quick. Please flag in here once the update is made and deployed

**Comment by demenech** [comment]
@nicolas-becker @osahon-okungbowa FIXED. It should be deployed soon along with other changes
