### ISSUE TITLE
Implement the Datasets Browse page design (no functionality logic)

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#40]
## Description
When I view the Datasets page design implementation for the data portal, I want to see a design implementation that matches the [Figma design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=12-20858&node-type=FRAME&t=R30kSWgwuTFdsRKI-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1091), so that it can be easily confirmed/validated that the UI/UX for the Datasets page is aligned with expectations

## Tasklist (TBD - to be completed by Developer assigned)
- Implement Search input
- Implement Quick Filters
- Re-use Datasets Filters
- Implement Dataset Results and Pagination

## Acceptance Criteria
given that i have access to the Dev instance and Figma design, then:
- [ ] when i view the Datasets page UI/UX design implementation on the Dev instance, it matches the Figma Design
- [ ] all agreed sections of the Datasets page Figma design are implemented with the same UI behaviour (**without** application logic/functionality) on the remote Dev instance

**Comment by osahon-okungbowa** [comment]
This can be viewed here https://tdc-data-portal.vercel.app/search

**Comment by osahon-okungbowa** [comment]
This can be viewed here https://tdc-data-portal.vercel.app/search

**Comment by nicolas-becker** [comment]
We decided that it would be great if you could also implement the modification we discussed last week, concerning the introduction of an "advanced filters" option, that hides the right-sided filters. Please include the "Years covered" and "Keyword" filters in the quick filter list and remove the "Service" filter instead. 

Do you think it is possible to adapt the filters appearing in the quick filter list according to their usage, once we have the Analytics running?

**Comment by osahon-okungbowa** [comment]
@nicolas-becker 
> Please include the "Years covered" and "Keyword" filters in the quick filter list and remove the "Service" filter instead.
in our opinion, the dropdown for the Keyword would be too large .

> Do you think it is possible to adapt the filters appearing in the quick filter list according to their usage, once we have the Analytics running?
this is currently out of scope, and would require significant analysis

**Comment by nicolas-becker** [comment]
@osahon-okungbowa 
I understand, thank you. Maybe we can discuss this point quickly this afternoon. But for now, let's just swap Service and Years covered, as we think that it is of more relevance.

As for the second point, no worries, it was just out of curiosity. Thanks for the reply!

**Comment by osahon-okungbowa** [comment]
@nicolas-becker sure, no problem. i've included this in our meeting discussion for today

**Comment by osahon-okungbowa** [comment]
@nicolas-becker 
i believe we can close this issue?

details agreed for the quicker filters are being implemented in #44
