### ISSUE TITLE
Implement the Functional Logic of the Signup flow

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#46]
As a none user of the TDC portal, I want to be able to sign up securely without needing to use email and password, as well as customize my experience based on my location, topics, organizations of interest, create new organization and invite my colleagues all during my onboarding process, so that I can be ready to maximize the capabilities of the portal immediately after I signup.

## Tasklist (TBD - to be updated by the developer)
* [x] #23
* [x] Get all organizations, topics and locations on the Data Interest tab.
* [x] Allow users to follow topics, locations and organizations.
* [x] Allow users to request organization owner to be part of the organization.
* [x] Allow users to request Sysadmin to create a new organization.
* [x] Allow users to invite other users.
 
## Acceptance Criteria
Given that I am a non user of the portal who wants to sign up,
* [x] i want to be able to sign up securely without using email and password
* [x] i can choose my location, topics, and organizations of interest, which are saved to my profile.
* [x] i can either select an existing organization or create a new one.
* [x] i can invite colleagues by entering their email addresses.
* [x] i am redirected to my dashboard after i have signed up.

**Comment by Uchechukwu-Onye-Igbo** [comment]
Registering a new organization is not expedient.

**Comment by muhammad-hassan11** [comment]
[Documentation](https://github.com/transport-data/tdc-data-portal/pull/99/files#diff-42de84da5aeeb382666c757585b9e78ab477a6cc9a7a7138adf2a0ce7b118e17R1)

[Integrations tests](https://github.com/transport-data/tdc-data-portal/pull/99/files#diff-6ae5664a945ff3537f0fe0e20459b5aacd636870a00b28f94b0087b8295c2070R1)

**Comment by Uchechukwu-Onye-Igbo** [comment]
### QA Feedback to Implementation

**Bugs to fix (high priority)**:
* When selecting organizations in the sign-up flow, the organization title should be displayed and not the slug.
* Check if the user’s selected locations, organizations, and topics are correctly followed after the sign-up process is completed. That is once the user goes to the next step.
* When a new request to add an organization is made, email to add such orgs should be sent to all the sysadmins. Also there should be success notification after the request to add the org is done.
* When a users invites other users (step 3 of the onboarding flow), an error occurs. Ideally, the invite should send an email to the email address the user wants to invite to join the portal.

**Improvements to make (low priority)**:
* If a user has previously followed an organization, it should be preselected during future interactions with the follow page/flow.

@muhammad-hassan11

**Comment by muhammad-hassan11** [comment]
@Uchechukwu-Onye-Igbo the feedback has been implemented

**Comment by Uchechukwu-Onye-Igbo** [comment]
QA Feedback

Hello @muhammad-hassan11, please fix these:

These issues happen for both existing user and new users
- On step 2: when i select an organisation to join, add message and click next. I get an error message saying: "Access denied: User philshisquare not authorized to read group 94861715-012e-4467-8353-ab6d1a9c32f9"
- Inviting a user to join us produces an error "An unknown error happened"
- when creating a request to add new organisation, i get an error saying: "unexpected error happened"

**Comment by Uchechukwu-Onye-Igbo** [comment]
> @Uchechukwu-Onye-Igbo issues flagged above are fixed. Please test again.

Thanks very much. I will do so and let you know.

**Comment by nicolas-becker** [comment]
Looks good, thank you! Two comprehension questions:

- According to the UI it is possible to skip step. Is it really possible to provide this information later on, i.e. after the profile has been set-up?
- If the user requests a new organization, will he/she be able to proceed with the creation of the user, until the request is accepted?

**Comment by muhammad-hassan11** [comment]
- Currently there is no way to provide this information later on. The only way is to hit the url, but there should be a link pointing to that page.
- User can proceed on with the creation of the user, until the new organization request is accepted. User will be created.

Cc: @osahon-okungbowa @Uchechukwu-Onye-Igbo

**Comment by Uchechukwu-Onye-Igbo** [comment]
> Looks good, thank you! Two comprehension questions:
> 
> * According to the UI it is possible to skip step. Is it really possible to provide this information later on, i.e. after the profile has been set-up?
> * If the user requests a new organization, will he/she be able to proceed with the creation of the user, until the request is accepted?

Hello @nicolas-becker to your questions,
- Yes, there is a way to return to the flow. The user only has to click on the signup button again to complete the steps they previously skipped.
- Yes. The first step of creating an account is a complete step. It is independent of whether or not they complete the other steps. After requesting a new organisation, yes the user can proceed with the other steps as well.

**Comment by nicolas-becker** [comment]
Thanks @Uchechukwu-Onye-Igbo and @muhammad-hassan11 for the clarifications! I will try to test this with a new account

**Comment by nicolas-becker** [comment]
@Uchechukwu-Onye-Igbo @muhammad-hassan11 

In addition to the discussion we had on wednesday, I was wondering if in the future, when we launch the productive version of the platform, the new user would still need to authorize Leonardo's GH Account to add him to the platform:

![Image](https://github.com/user-attachments/assets/5fff6042-ea36-4178-b82e-ba51d5c47c93)

I guess not, because this of course doesn't look very trustworthy to someone who doesn't know that Leonardo (or whoever manages the github access in the future) is affiliated with Datopian or TDC. So the question is: how will this process look like in the future?

**Comment by demenech** [comment]
hey @nicolas-becker 

This happens because we are currently using a GitHub app created by Leonardo for development purposes. For Production, you will have to create a new GitHub app (see https://github.com/settings/apps) and then we'll configure the deployment to use this new app.

**Comment by nicolas-becker** [comment]
Hi @demenech thanks for the reply! I will create a new GitHub App under the [transport-data](https://github.com/transport-data) organization, so I hope my personal username will not appear to the user when signing up.

For this I would need some guidance for the configuration, e.g.:
- the "Homepage URL": Can I insert the organization's [url](https://github.com/transport-data) or the Data Portal repo [url](https://github.com/transport-data) here?
- the callback URL: Reading the docs it seems like this is required when using user access tokens. 
- the webhook settings

Thank you for your assistance!

**Comment by demenech** [comment]
hi @nicolas-becker 

If you use the organization I think it will work out as expected.

For the values, try with:

- Homepage URL => https://tdc-data-portal.vercel.app (this can be updated later on to a different domain)
- Callback URL => Same as above
- Webhook settings => Leave it empty

Then, you'll have to share with us (on private!) the client ID and client secret.

One other setting that is needed is on Permissions. Under account permissions, please set it so that we require read-only access to the user's email addresses:

![image](https://github.com/user-attachments/assets/4e2bb3c0-f489-4454-9d69-3d2e45069150)

Let me know if you need help with anything.

**Comment by nicolas-becker** [comment]
Hi @demenech thanks for the instructions! I just sent you the required infos via chat on Teams. Let me know if you need any further info

**Comment by demenech** [comment]
hi @nicolas-becker 

Flagging I forwarded the credentials to Meiran so that this can be deployed to prod. Many thanks.
