### ISSUE TITLE
Implement Login page design (no functionality logic)

### ISSUE THREAD

**Issue by osahon-okungbowa** [transport-data/tdc-data-portal#5]
## Description
when i view the Login Page design implementation for the data portal, I want to see a design implementation that matches the [Figma design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?page-id=0%3A1&node-id=645-70098&viewport=-3049%2C-751%2C0.24&scaling=min-zoom&starting-point-node-id=5%3A1091), so that it can be easily confirmed/validated that the UI/UX for the Login page is aligned with expectations

## Tasklist (TBD - to be completed by Developer assigned)
- [x] Layout development
- [x] ~~Email validation~~
- [x] ~~Save data on cookies~~

## Acceptance Criteria
given that i have access to the Dev instance and Figma design, then:
- [x] when i view the Login page UI/UX design implementation on the Dev instance, it matches the Figma Design
- [x] all agreed sections of the Login page Figma design are implemented with the same UI behaviour (**without** application logic/functionality) on the remote Dev instance

**Comment by nicolas-becker** [comment]
Works well! Two minor comments:

- Is it possible to center the line between the names of the steps? (Please compare attached screenshot and Figma design)
![image](https://github.com/user-attachments/assets/669c9b51-56de-45b2-a2eb-73ed499da07a)
- We should fill the empty green button on the right under the "Organisation" step. Maybe "Reach out" and link to the contact form? 

Thanks!

**Comment by Gutts-n** [comment]
@nicolas-becker Thank you for the comment, I've pushed the required changes pls take a look :)

**Comment by nicolas-becker** [comment]
Perfect, thank you!
