### ISSUE TITLE
Implement the functional logic of the Topics page

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#54]
As a user of the TDC portal, I want to be able to easily search for datasets, browse different topics of interest and see the stats of the most viewed datasets, so that I can quickly find the information relevant to my interest.

Figma [link](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=10-19597&node-type=frame&t=ouOGVUIkK8KWcHbj-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1091)

## Tasklist (TBD - updated by the developer)
* [add tasks]

## Acceptance
Given that I am on the TDC data portal and want to search for data,
* [x] I can search for datasets and see filtered results related to my search query
* [x] I can browse various topics with clear dataset listings.
* [x] I can click the listed data to go to the dataset details page of that data

**Comment by Uchechukwu-Onye-Igbo** [comment]
Hi @luccasmmg, this looks good. I have just an improvement suggestion though.

keep the height of the tiles fixed. move the see all buttons to the buttom of all the tiles so that things are balanced and more visually impressive.

![Image](https://github.com/user-attachments/assets/c25e434c-6147-413c-b866-462a5249054c)

**Comment by luccasmmg** [comment]
Done, deployment in about 10 minutes

**Comment by nicolas-becker** [comment]
The functionality is fine, thank you. 

I noticed that the quality of the icons for the topic is low. I tried to add a new icon to the test topic "QA topic Oct 4", appearently the quality is decreased after uploading the image. Maybe this belongs to a separate issue though

**Comment by Uchechukwu-Onye-Igbo** [comment]
> The functionality is fine, thank you.
> 
> I noticed that the quality of the icons for the topic is low. I tried to add a new icon to the test topic "QA topic Oct 4", appearently the quality is decreased after uploading the image. Maybe this belongs to a separate issue though

Hi @nicolas-becker, @luccasmmg will work on improving this. It happens because of image optimization.

**Comment by nicolas-becker** [comment]
This seems to be implemented now. Would it be possible to update the "most viewed" and "TDC harmonized" icons in better resolution?

**Comment by luccasmmg** [comment]
Sure, just ask your design guys to get me an SVG version of those icons

**Comment by nicolas-becker** [comment]
Sadly we don't have design guys at TDC, and we can't locate the icons used for Figma. Would be fine for now to use some better screenshots of the icons from the figma, e.g. 
![Image](https://github.com/user-attachments/assets/e6814de1-5be4-41bb-8dbb-79641987fed6)

Would be great if you could provide some description how to change the icons in the future, once we have SVGs. Thanks

**Comment by luccasmmg** [comment]
I cant download the image you sent (Its giving me an unauthorized error) but you can change it yourself, its just the topic image, video explaining below and docs [here](https://github.com/transport-data/tdc-data-portal/tree/main/docs/topics) 

[Screencast from 2024-11-05 15-20-25.webm](https://github.com/user-attachments/assets/f0d885bd-3ff8-4b5a-bb18-9d90cf3df59f)

**Comment by nicolas-becker** [comment]
Thanks @luccasmmg , yes I've been exploring this option and it works. I was rather asking for the two icons that are not attached to a topic:

![image](https://github.com/user-attachments/assets/5837bbf0-847d-4268-9a91-ba1c3707fd0b)

Is it possible for us to change them?

**Comment by luccasmmg** [comment]
Sure, can you send new ones on teams?

**Comment by nicolas-becker** [comment]
Hi @luccasmmg I had sent you the icons on teams, did you receive them? For me to close this issue, please insert them and quickly notify me. Or even better, please point where we can modify the icons on our own (not for topics but for the TDC Harmonized and Most Viewed labels)

**Comment by luccasmmg** [comment]
Here are the files https://github.com/transport-data/tdc-data-portal/tree/main/frontend/public/images/icons
Here they are used https://github.com/transport-data/tdc-data-portal/blob/main/frontend/src/pages/datasets.tsx#L95

**Comment by nicolas-becker** [comment]
Thanks @luccasmmg I've just updates the icons and it looks fine now. 

I also noticed that @Gutts-n must have been using the TDC icons for this overview and wondering where you got the icons from? It would be great if you could share them with us, so we can use them in the future. Thanks!

![image](https://github.com/user-attachments/assets/98f4c163-d067-4122-88b6-911ba74f9b30)
