### ISSUE TITLE
Implement the functional logic of the Data Provider Page for the TDC Portal

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#55]
As a data provider, I want to easily submit my datasets, see information about how TDC works, organisations already providing data there, understand the reasons why I should contribute my data, have clear guidance on how to add my data, and find answers to common questions, so that I can be well-educated about the platform and confidently contribute my data to the TDC repository.

## Tasklist (TBD - updated by the developer)
* [add data}

## Acceptance Criteria
Given that I am on the TDC portal and I want to add data,
* [x] I see a dedicated page based on this figma [design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=725-135022&node-type=FRAME&t=R30kSWgwuTFdsRKI-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1091) to educate me and allow me add my data
* [x] I will be directed to the log in page first if I am viewing this pages without being logged in, once I login, I should be lead to the data upload process.

**Comment by Uchechukwu-Onye-Igbo** [comment]
What happens when “add data" is clicked:

- If the user is not logged in, display a pop-up informing them that they need to log in. Once they log in, allow them to proceed to the creation process once they click the button. However, if they don’t have the necessary permissions, the action should fail with an appropriate error message after they follow through.

**Comment by nicolas-becker** [comment]
One small adaptation: 
The "add data" should lead to the sign up-page, if the user is not logged in, such as previously reflected by @Uchechukwu-Onye-Igbo . Currently it is leading to the Log in-page (which can be recognized by the "Welcome back" message): 

![Image](https://github.com/user-attachments/assets/4e973b8d-bc56-43d0-98ea-52b08d70d12f)

**Comment by Uchechukwu-Onye-Igbo** [comment]
> One small adaptation: The "add data" should lead to the sign up-page, if the user is not logged in, such as previously reflected by @Uchechukwu-Onye-Igbo . Currently it is leading to the Log in-page (which can be recognized by the "Welcome back" message):
> 
> ![Image](https://private-user-images.githubusercontent.com/56161155/380206975-4e973b8d-bc56-43d0-98ea-52b08d70d12f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjkwMjksIm5iZiI6MTcyOTg2ODcyOSwicGF0aCI6Ii81NjE2MTE1NS8zODAyMDY5NzUtNGU5NzNiOGQtYmM1Ni00M2QwLTk4ZWEtNTJiMDhkNzBkMTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDE1MDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NjQzYWNmNmY1NzE3ZjAxNDg1NjRkMjNmOGNjNDU5MTJiMzZhY2ZmYWJmNTMzZDQ1YmY4NDgzZmYzN2Y0MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3XUThgdtR2H9i8xgbn04IGCUznTvqe89I-QoCMPSCII)

hI @nicolas-becker i think it makes sense the way we have it. Because there is not way to know if a user who is not logged in has an account or not. if we will tell all users to signup, that will affect existing users who are not logged in at the moment.

but the important thing is, if a user who has no account clicks the button, they will be led to create and account and at the end be logged in and redirected to add the data.

so it make more sense the way it was implemented. let me know if you agree.

**Comment by nicolas-becker** [comment]
I agree, that's fine for me too. I'll move the issue to done
