### ISSUE TITLE
Implement the functional logic of the About Us Page for the TDC Portal

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#56]
As a user, I want to see information about TDC, the participating organisations, and the team behind the project, so that I can be well-informed about the organisations and the people contributing to it and managing the data.

## Tasklist (TBD - updated by the developer)
* [x] Sort events asc
* [x] Add link to Discussions Board
* [x] Documentation of the page
* [x] Documentation of how to manage people

## Acceptance Criteria
Given that I am on the TDC portal,
* [ ] I see a dedicated page based on this figma [design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=10-12457&node-type=FRAME&t=R30kSWgwuTFdsRKI-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1091) educating me about the TDC, it organisations and people. 
* [ ] i can click on the link in communities section of the page and be redirected to github

**Comment by Uchechukwu-Onye-Igbo** [comment]
Note: Add the discussions page [link ](https://github.com/orgs/transport-data/discussions)to the community section of the page

**Comment by willy1989cv** [comment]
Doc: https://github.com/transport-data/tdc-data-portal/tree/main/docs/home-page
Test: https://github.com/transport-data/tdc-data-portal/actions/runs/11266081869/job/31328986006#step:14:293

**Comment by Uchechukwu-Onye-Igbo** [comment]
QA Feedback

The discussion link should be updated to this: https://github.com/orgs/transport-data/discussions/categories/user-feedback 

@Gutts-n please can you update it?

**Comment by Gutts-n** [comment]
I see that there is the same link on the data provider page, do you want me to change it as well? @Uchechukwu-Onye-Igbo

**Comment by Uchechukwu-Onye-Igbo** [comment]
> I see that there is the same link on the data provider page, do you want me to change it as well? @Uchechukwu-Onye-Igbo 

Yes please.

**Comment by nicolas-becker** [comment]
Hi @Uchechukwu-Onye-Igbo @willy1989cv  , I have been trying to add new TDC member porfiles to the About Us page (as indicated in the docs: https://github.com/transport-data/tdc-data-portal/tree/main/docs/static-pages/people) but I get a failure message: 

![Image](https://github.com/user-attachments/assets/54a5b399-2f63-4784-b39a-63bc2f45c46d)

I am not able to access the details as I don't have access to the Vercel account.

**Comment by Uchechukwu-Onye-Igbo** [comment]
> Hi @Uchechukwu-Onye-Igbo @willy1989cv  , I have been trying to add new TDC member porfiles to the About Us page (as indicated in the docs: https://github.com/transport-data/tdc-data-portal/tree/main/docs/static-pages/people) but I get a failure message: 
> 
> ![Image](https://github.com/user-attachments/assets/54a5b399-2f63-4784-b39a-63bc2f45c46d)
> 
> I am not able to access the details as I don't have access to the Vercel account.

@willy1989cv kindly take a look at this.

**Comment by nicolas-becker** [comment]
Update: this is working again. But I would be thankful for a brief explanation in order to know how to react to this issue in the future (maybe add to docs). Thanks 

@Uchechukwu-Onye-Igbo @willy1989cv

**Comment by Uchechukwu-Onye-Igbo** [comment]
> Update: this is working again. But I would be thankful for a brief explanation in order to know how to react to this issue in the future (maybe add to docs). Thanks
> 
> @Uchechukwu-Onye-Igbo @willy1989cv

@willy1989cv kindly explain

**Comment by willy1989cv** [comment]
@nicolas-becker @Uchechukwu-Onye-Igbo it seems like it is an error on deployed vercel caused when building the static page "Dashboard". I am fixing it

**Comment by willy1989cv** [comment]
@nicolas-becker @Uchechukwu-Onye-Igbo this issue have been addressd in this PR: https://github.com/transport-data/tdc-data-portal/pull/191
After Peer-Review will merge and ask to test again

**Comment by nicolas-becker** [comment]
Thanks!
