### ISSUE TITLE
Implement the partners and donors page of the portal

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#57]
When I visit the data portal, I want to view the logos of the partners and donors of the TDC, so I can be informed about the organisations backing the program and contributing to it.

## Tasklist (TBD - added by the developer)
- [x] Added link to "/contact"
- [x] Github content with donor/partner title, name and website
- [x] Documentation

## Acceptance Criteria
Given that I am on the portal,
* [ ] I can to view a page based on this figma [design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=135-32766&node-type=FRAME&t=R30kSWgwuTFdsRKI-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1091)
* [ ] I can to see a the logos of TDC's partners and donors.

**Comment by Verena205** [comment]
Reacting to the question/action item: "TDCI needs to provide a link to the "Become a Partner/Donor" button on the Partners & Donors page. does this link to Github sponsor, Stripe etc"

This should link to the [contact@transport-data.org](mailto:contact@transport-data.org) adress to send an email to us / alternatively leed to the contact us page

**Comment by willy1989cv** [comment]
Doc: https://github.com/transport-data/tdc-data-portal/tree/main/docs/partners-donors
Test:
