### ISSUE TITLE
Investigate the suitability of the alternative web analytics tool suggested by TDC

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#64]
When managing web analytics for the TDC portal, I want to investigate the suitability of [Matomo](https://matomo.org/) a web analytics tool suggested by TDC, so that I can determine if it meets the portal's needs in terms of functionality, user behavior tracking, and reporting capabilities.

## Tasklist (TBD - to be updated by the developer)
* [add tasks]

## Acceptance Criteria
Given that I want use [Matomo](https://matomo.org/) for web tracking on the portal frontend, 
* [ ] I can perform basic web analytics functions, including page views, event tracking, downloads, etc.
* [ ] I can carry-out customized reporting of user behavior on the portal
* [ ] I can seamlessly integrate it smoothly with the current TDC tech stack without requiring extensive custom development.

**Comment by luccasmmg** [comment]
Overall it seems fine to integrate Matomo, i was able to set it up to track events on our development portal and was able to retrieve those events using their API
