### ISSUE TITLE
Setup the Staging Environment for the data portal services/components

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#66]
## Description
As a DevSecOps Engineer, I want to setup a staging environment for the data portal services/components, so that the development team can easily test all incremental functionalities and features for the portal in an environment similar to the dev  instances. 
Config repo: https://github.com/datopian/dx-helm-tdc - is has staging branch for STAGING environment, PRODUCTION will use same config repo but with tags. 

## Tasklist
- [x] Deploy CKAN staging site: https://ckan.tdc.staging.datopian.com/
- [x] Deploy FRONTEND staging site: https://frontend.tdc.staging.datopian.com/

## Acceptance Criteria
given that I have access to the staging instance URL, then:
- [x] when I have the URL, the portal load for me without errors
   - [x] that the front end app of the portal lives in the infrastructure and not on vercel.
- [x] the staging environment has all the services/components required for the data portal
- [x] all services and components of the data portal are running without errors
  - [x] CKAN DMS
  - [x]  Portal.js Frontend app running on Vercel
  - [x] all CKAN services

**Comment by Mikanebu** [comment]
@Uchechukwu-Onye-Igbo I Moved this task to peer-review section. It is done.

**Comment by nicolas-becker** [comment]
Is there a need/way for us to test this issue for acceptance?
