### ISSUE TITLE
Populate default options for metadata fields (sectors, modes, regions and geographies)

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#77]
When creating datasets, I want to have standardized options available for control vocabulary fields, so that I can ensure that the users can only selected validated values from the fields.

## Tasklist (TBD - updated by the developer)
* [x] Populate the options for sectors, modes and services based on https://docs.google.com/spreadsheets/d/1kjYlJX8W0JzVZSUSK7waq9OqXs0WPmuF/edit?gid=2073930220#gid=2073930220
* [x] Create a CLI command that will create the default geographies based on the UN geoscheme regions.

## Acceptance Criteria
* [x] There is a CLI command to create geographies, sub regions and regions
* [x] In the schema definition file, the choice for sectors and modes are populated with valid values 

Given that I want to create a dataset on the TDC portal,
* [x] I am able to select values for fields for sectors, modes, regions and geographies that are valid based on the metadata schema.

**Comment by demenech** [comment]
PR: https://github.com/transport-data/tdc-data-portal/pull/87

**Comment by nicolas-becker** [comment]
I am currently only seeing the options for geographies (countries and regions): 
![image](https://github.com/user-attachments/assets/333ecdf5-3da8-4fb8-9f30-10d3f4499948)

**Comment by demenech** [comment]
hello @nicolas-becker 

I think this form is not entirely wired up yet.

Currently, the only way to validate the fields would be:

- Sectors and modes - Check the current schema https://ckan.tdc.dev.datopian.com/api/action/scheming_dataset_schema_show?type=dataset . Look for "sectors" and "modes" and you should see a list of "choices".
- Geographies/Regions - You can find the current list at https://ckan.tdc.dev.datopian.com/api/3/action/group_list?&all_fields=True&include_extras=True&type=geography - But I suggest that you take a look at the documentation for a better overview of the entire list https://github.com/transport-data/tdc-data-portal/tree/main/docs/geographies#list-of-default-geographies

**Comment by nicolas-becker** [comment]
Perfect, thank you!
