### ISSUE TITLE
Implement the UN issued Map on the Geography Page

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#88]
As a user of the TDC portal, I want to see a map on the geography page that shows countries validated by the UN, so that I can view accurate and authoritative geographic information in line with international standards.

## Related Issues
- #43 

## Tasklist (TBD - updated by the developer)
* [add tasks]

## Acceptance Criteria
Given that I am reviewing the this implementation and I have access to the geography page, 
* [x] I can see a map based on [this file](https://drive.google.com/file/d/1O7TKJjAP6-JPU9cwS1p2QnDiIRgLRrHy/view?usp=drive_link) shared by the TDCI team
* [x] I can see that the map implemented is styled according to this [figma design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=10-26857&node-type=FRAME&t=R30kSWgwuTFdsRKI-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1091)
* [x] clicking on a country within the map leads to the Dataset Browse page

## Text from the UN to add to the map

**Description**

The United Nations Geospatial Data, or Geodata, is a worldwide geospatial dataset of the United Nations.

The United Nations Geodata is provided to facilitate the preparation of cartographic materials in the United Nations includes geometry, attributes and labels to facilitate the adequate depiction and naming of geographic features for the preparation of maps in accordance with United Nations policies and practices.

The geospatial datasets here included are referred to as UN Geodata simplified and are generalized based on UNGeodata 25 million scale.

The feature layers include polygons/areas of countries (BNDA_simplified), lines for international boundaries and limits (BNDL_simplified), and major water body (WBYA_simplified). In addition, aggregated regional areas are available following M49 methodology (GEOA_simplified, SUBA_simplified, INTA_simplified) and SDG regional grouping (SDGA_simplified).

The UN Geodata simplified is prepared in the context of the Administrative Instruction on the “Guidelines for the Publication of Maps” and should serve global mapping purposes as opposed to local mapping. The scale is unspecific for the United Nations Geodata simplified and is suitable for generalized world maps and web-maps.

**Terms of Use**

The boundaries and names shown and the designations used on this map do not imply official endorsement or acceptance by the United Nations. (short form)

The designations employed and the presentation of material on this map do not imply the expression of any opinion whatsoever on the part of the Secretariat of the United Nations concerning the legal status of any country, territory, city or area or of its authorities, or concerning the delimitation of its frontiers or boundaries. (long form)

Final boundary between the Republic of Sudan and the Republic of South Sudan has not yet been determined.

Dotted line represents approximately the Line of Control in Jammu and Kashmir agreed upon by India and Pakistan. The final status of Jammu and Kashmir has not yet been agreed upon by the parties.

A dispute exists between the Governments of Argentina and the United Kingdom of Great Britain and Northern Ireland concerning sovereignty over the Falkland Islands (Malvinas).

* Non-Self-Governing-Territories

**Credits**

United Nations Geospatial

**Comment by Gutts-n** [comment]
@Uchechukwu-Onye-Igbo and @osahon-okungbowa 

How will we implement this plus symbol? When the datasets are in the middle of the decimal we decrease the value to the first one at the beginning of the decimal and put a plus symbol? When it's an exact number like 20 datasets in a given country, do we show 15+? or just 20?

![Image](https://github.com/user-attachments/assets/5bcddd1f-10d7-4471-973b-a55bb3f6ff8a)

**Comment by Gutts-n** [comment]
Moved to blocked because I need an answer to the question above.

cc: @Uchechukwu-Onye-Igbo and @osahon-okungbowa

**Comment by osahon-okungbowa** [comment]
@Gutts-n your question has been answered in our internal standup

**Comment by Gutts-n** [comment]
Tests: https://github.com/transport-data/tdc-data-portal/actions/runs/11297632578/job/31424895979#step:14:680
Doc: https://github.com/transport-data/tdc-data-portal/blob/main/docs/geographies/README.md

**Comment by nicolas-becker** [comment]
Thank you! Could you please just add a few words to the docs on how to make adaptations to the default geography list, in case needed some day? 

I also noted that the map does not have the same responsiveness for all countries, e.g. when hovering over Algeria or Kazakhstan. 

The disputed borders look way better now, thank you!

**Comment by Gutts-n** [comment]
Hello @nicolas-becker thank you for the feedback. 

I'll add more information to the docs 👍 

The second point is a bit complicated because the borders of these specific countries are smaller than the others, bringing the impression that the country didn't expand its size when the cursor hovers over it, a way to fix it would be to reduce the thickening of the borders as it was before the update but it would affect the visual of the borders, unfortunately.

**Comment by nicolas-becker** [comment]
Hi Leonardo, thanks for your response and for the implemented documentation! 

Two follow-up questions:
1) Which credentials are required to access the DMS? 
2) What exactly is meant with "Avoid changing the geography name"? --> What is the exact information we should not change?

Regarding the borders I think it would be nice to have the same visual effect for all countries. If this is not/hardly possible than it would be preferable to drop this animation. Thank you!

**Comment by Gutts-n** [comment]
Hello @nicolas-becker , to sign in on DMS we use generally the sys admin credentials I can't share them here in the comments because the board is public, but I'll send them to you on teams.

About the avoid changing the geography name I mean that you can't change this URL field: 
![image](https://github.com/user-attachments/assets/78e101d5-45c4-4f7d-ad7b-2993374b38b8)

We use the iso 3 of each country to get the flags maps and search datasets on the application.

**Comment by nicolas-becker** [comment]
Perfect, thanks for the clarification! @Gutts-n I'll close the issue
