### ISSUE TITLE
Update the readme of the TDC repository to align with the actual implementation/documentation of the project

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#89]
As a developer or contributor to the TDC project, I want an up-to-date README in the repository that details the implementation, dependencies, and links the user guide of features, so that I can easily understand the project's state, its features, and how to use them effectively.

## Tasklist (TBD - updated by the developer)
* [add tasks]

## Acceptance Criteria
Given that I have access to the TDC repository for the portal,
* [ ] I can see an updated readme that provides me detailed information about the project
* [ ] I can find links that links me to the independent user guides for the implemented features

**Comment by osahon-okungbowa** [comment]
note: this ticket updates the REadsme as at the time of the Sprint. 

We will have another ticket toward the end of the project to do one last refresh of the Readmes

**Comment by nicolas-becker** [comment]
Hi @luccasmmg, thanks for the detailed documentation, this is great. I was just looking for two specific topics but was not able to find them yet:

- the footer.
- the lower part of the FAQ page, which I am not sure if it is reflected here: https://github.com/transport-data/tdc-data-portal/tree/main/docs/static-pages/faq. Specifically I would be interested if there's functionality attached to this section: 

![Image](https://github.com/user-attachments/assets/4c4f83d2-2330-4798-b437-443c64d7fe1a)

Could you please point to the related sections of the docs or add some info if necessary? Thanks!

**Comment by luccasmmg** [comment]
> Hi @luccasmmg, thanks for the detailed documentation, this is great. I was just looking for two specific topics but was not able to find them yet:
> 
> * the footer.
> * the lower part of the FAQ page, which I am not sure if it is reflected here: https://github.com/transport-data/tdc-data-portal/tree/main/docs/static-pages/faq. Specifically I would be interested if there's functionality attached to this section:
> 
> ![Image](https://private-user-images.githubusercontent.com/56161155/391897803-4c4f83d2-2330-4798-b437-443c64d7fe1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzA5NTksIm5iZiI6MTczMzIzMDY1OSwicGF0aCI6Ii81NjE2MTE1NS8zOTE4OTc4MDMtNGM0ZjgzZDItMjMzMC00Nzk4LWI0MzctNDQzYzY0ZDdmZTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEyNTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0OGJlZTFlN2FkZGQ5Zjg0YWRmOTQ0NzVjNzY5NjZjNTBkOTQ1ZmYzMDU1NzRiMzIwZDViMjYwYTYzZWJjMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uuJnkQFetN-AZJ0Px2QkVZjuIa7eHrVbznHd0HcDYjE)
> 
> Could you please point to the related sections of the docs or add some info if necessary? Thanks!

@nicolas-becker i think TDC agreed that this would be removed since it would require you guys to maintain the contact infrastructure, but no further conversations were had, @Uchechukwu-Onye-Igbo will have more context

**Comment by Uchechukwu-Onye-Igbo** [comment]
> Hi @luccasmmg, thanks for the detailed documentation, this is great. I was just looking for two specific topics but was not able to find them yet:
> 
> * the footer.
> * the lower part of the FAQ page, which I am not sure if it is reflected here: https://github.com/transport-data/tdc-data-portal/tree/main/docs/static-pages/faq. Specifically I would be interested if there's functionality attached to this section:
> 
> ![Image](https://private-user-images.githubusercontent.com/56161155/391897803-4c4f83d2-2330-4798-b437-443c64d7fe1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzE0MDMsIm5iZiI6MTczMzIzMTEwMywicGF0aCI6Ii81NjE2MTE1NS8zOTE4OTc4MDMtNGM0ZjgzZDItMjMzMC00Nzk4LWI0MzctNDQzYzY0ZDdmZTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEzMDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MTA4NjI2MWU0ODI0YWM5ZjI1ZjcyYjY1ZjNiYzAzYmU1NTFhMTdmNWY1ZDk5ZmExZjNkY2ZlNTNiOWVmYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aRejvqjMjaog9oLX3K6C33ZPLeQsjUQqWWeiFBFi6QA)
> 
> Could you please point to the related sections of the docs or add some info if necessary? Thanks!

hello @nicolas-becker if you recall, we agreed to use github discussions for the contacts. the section in question was based on the design in figma. but the form was not implemented. we can go ahead and remove it now.

**Comment by nicolas-becker** [comment]
@Uchechukwu-Onye-Igbo @luccasmmg Yes I recall the conversation, thanks. As agreed, please proceed to remove this section if it has not been implemented. 

 Could you please also add the link to GHD on this button? I believe it is missing:
![image](https://github.com/user-attachments/assets/fe2500fa-1104-4a82-8c90-dc92adefa522)

Thank you!

**Comment by luccasmmg** [comment]
@nicolas-becker already implemented the changes, should be live in about 10 minutes
